apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: guestbook
spec:
  failover:
    application:
      decisionConditions:
        tolerationSeconds: 30
      gracePeriodSeconds: 30
      purgeMode: Graciously
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: guestbook-ui
    - apiVersion: v1
      kind: Service
      name: guestbook-ui
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    spreadConstraints:
      - maxGroups: 1
        minGroups: 1
        spreadByField: cluster
